# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OPTIMAL-IPB
                                 A QGIS plugin
 This plugin adds an algorithm to calculate palm tree on high resolution imagery based on machine learning
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-09-22
        copyright            : (C) 2020 by Muhammad Nurdin
        email                : muhanur@apps.ipb.ac.id
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Muhammad Nurdin'
__date__ = '2020-09-22'
__copyright__ = '(C) 2020 by Muhammad Nurdin'

import os
import sys

# Inject qgis_gdal_env so the plugin finds its dependencies (tensorflow/tf_keras,
# lsnms, pandas, etc.) without requiring them in QGIS's own Python installation.
_CONDA_ENV = r"C:\Users\suily\miniconda3\envs\qgis_gdal_env"
_site_pkgs = os.path.join(_CONDA_ENV, "Lib", "site-packages")
if os.path.isdir(_site_pkgs) and _site_pkgs not in sys.path:
    sys.path.insert(0, _site_pkgs)
for _dll_subdir in ("Library\\bin", "Library\\mingw-w64\\bin", ""):
    _dll_path = os.path.join(_CONDA_ENV, _dll_subdir) if _dll_subdir else _CONDA_ENV
    if os.path.isdir(_dll_path):
        os.add_dll_directory(_dll_path)


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OPTIMAL-IPB class from file OPTIMAL-IPB.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .optimal_ipb import OptimalIpbPlugin
    return OptimalIpbPlugin(iface)
