# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OPTIMAL-IPB
                                 A QGIS plugin
 This plugin adds an algorithm to calculate palm tree on high resolution imagery based on machine learning
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-09-22
        copyright            : (C) 2020 by Muhammad Nurdin
        email                : muhanur@apps.ipb.ac.id
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from __future__ import division

__author__ = 'Muhammad Nurdin'
__date__ = '2020-09-22'
__copyright__ = '(C) 2020 by Muhammad Nurdin'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsGeometry,
                       QgsCircle,
                       QgsPointXY,
                       QgsPoint,
                       QgsPolygon,
                       QgsFields,
                       QgsField,
                       QgsFeature,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFeatureSink,
                       QgsMessageLog)

import numpy as np
import os

from lsnms import nms
from osgeo import gdal

from qgis.PyQt.QtCore import QVariant
from qgis.PyQt.QtWidgets import QMessageBox

import onnxruntime as ort
from .keras_retinanet.utils.image import preprocess_image, resize_image

from .helpers import sliding_window
from .helpers import pixel2coord
from .helpers import map_uint16_to_uint8

bboxes = []
scoreses = []
modelsList = []
outputType = ["Point", "Bounding Box", "Circle"]

cmd_folder = os.path.dirname(os.path.abspath(__file__))

class minmax:
    def __init__(self, minimum, maximum):
        self.minimum = minimum
        self.maximum = maximum

def detect_palm(model, ds, x, y, winW, winH, minmaxlist, scorethreshold):
    # crop image
    a_image = ds.ReadAsArray(x, y, winW, winH)
    datatype = ds.GetRasterBand(1).DataType

    normalizedImg = []

    if not datatype == 1:
        for i in range(3):
            band_255 = map_uint16_to_uint8(a_image[i], int(minmaxlist[i].minimum), int(minmaxlist[i].maximum))
            normalizedImg.append(band_255)

        normalizedImg = np.dstack((normalizedImg[2], normalizedImg[1], normalizedImg[0]))

    else:
        normalizedImg = np.dstack(((a_image[2],a_image[1],a_image[0])))

    # preprocess image for network
    image = preprocess_image(normalizedImg)
    image, scale = resize_image(image)

    # process image via onnxruntime (model is an ort.InferenceSession)
    input_name = model.get_inputs()[0].name
    outputs = model.run(
        None,
        {input_name: np.expand_dims(image, axis=0).astype(np.float32)}
    )
    output_names = [o.name for o in model.get_outputs()]
    boxes  = outputs[output_names.index('filtered_detections')]
    scores = outputs[output_names.index('filtered_detections_1')]
    labels = outputs[output_names.index('filtered_detections_2')]

    # correct for image scale
    boxes /= scale

    # select indices which have a score above the threshold
    indices = np.where(scores[0, :] >= scorethreshold)[0]

    # select those scores
    scores = scores[0][indices]

    # find the order with which to sort the scores
    scores_sort = np.argsort(-scores)

    # select detections
    image_boxes = boxes[0, indices[scores_sort], :]

    for i in range(len(image_boxes)):
        b = np.array(image_boxes[i,:]).astype(int)
        x1 = b[0] + x
        y1 = b[1] + y
        x2 = b[2] + x
        y2 = b[3] + y
        bboxes.append([x1, y1, x2, y2])

    scoreses.append(scores)

def geom_type(argument):
    switcher = {
        0: 1,
        1: 3,
        2: 3,
    }
    return switcher.get(argument, 3)

class OptimalIpbAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    OPTIMAL = 'MODEL'
    mAP = 'mAP'
    TYPE = 'TYPE'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        modelsList.clear()
        models_dir = os.path.join(cmd_folder, 'models')
        QgsMessageLog.logMessage(f'OPTIMAL-IPB: cmd_folder={cmd_folder}', 'OPTIMAL-IPB')
        try:
            for file in os.listdir(models_dir):
                if file.endswith(".onnx"):
                    modelsList.append(file)
        except Exception as e:
            QgsMessageLog.logMessage(f'OPTIMAL-IPB: models dir error: {e}', 'OPTIMAL-IPB')
        QgsMessageLog.logMessage(f'OPTIMAL-IPB: models found={modelsList}', 'OPTIMAL-IPB')

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT,
                self.tr('Input raster layer'),
                [QgsProcessing.TypeRaster]
            )
        )

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterEnum(
                self.OPTIMAL,
                self.tr('Select Models'),
                options=modelsList,
                defaultValue=0,
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                name=self.mAP,
                description=self.tr('mAP (mean Average Precision)'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=0.5,
                optional=False,
                minValue=0,
                maxValue=1
            )
        )
        
        self.addParameter(
            QgsProcessingParameterEnum(
                self.TYPE,
                self.tr('Select output type'),
                options=outputType,
                defaultValue=0,
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output Layer'),
                QgsProcessing.TypeVectorAnyGeometry
            )
        )

        if len(modelsList) <= 0:
            QMessageBox.information(None, 'OPTIMAL-IPB Plugins', 'You dont have models downloaded yet. Please download latest model from our repository through this link: <a href="https://github.com/p4wlppmipb/OPTIMAL-IPB/releases">https://github.com/p4wlppmipb/OPTIMAL-IPB/releases</a> and follow the instruction.')

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        iouthreshold = 0.5
        (winW, winH, stepSize) = (500, 500, 470)

        # load model
        model_name = modelsList[self.parameterAsEnum(parameters, self.OPTIMAL, context)]
        model = ort.InferenceSession(
            os.path.join(cmd_folder, 'models', model_name),
            providers=['CPUExecutionProvider']
        )

        # get CRS from raster source
        source = self.parameterAsRasterLayer(parameters, self.INPUT, context)
        ds = gdal.Open(source.source())
        width = ds.RasterXSize
        height = ds.RasterYSize
        rastercount = ds.RasterCount
        datatype = ds.GetRasterBand(1).DataType
        minmaxlist = []

        for bandId in range(ds.RasterCount):
            bandId = bandId + 1
            band = ds.GetRasterBand(bandId)
            band_arr_tmp = band.ReadAsArray()
            min, max = np.percentile(band_arr_tmp, (2, 98))
            minmaxlist.append( minmax(min, max) )

        mAP_val = self.parameterAsDouble(parameters, self.mAP, context)
        for (x, y) in sliding_window(width, height, stepSize):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break

            # Stop sliding windows if widows end
            if x + winW > width and y + winH > height:
                xl = width - winW
                yl = height - winH
                detect_palm(model, ds, xl, yl, winW, winH, minmaxlist, mAP_val)
                continue

            if x + winW > width:
                xl = width - winW
                detect_palm(model, ds, xl, y, winW, winH, minmaxlist, mAP_val)
                continue

            if y + winH > height:
                yl = height - winH
                detect_palm(model, ds, x, yl, winW, winH, minmaxlist, mAP_val)
                continue

            detect_palm(model, ds, x, y, winW, winH, minmaxlist, mAP_val)

        if bboxes:
            bboxeses = np.array(bboxes, dtype=np.float32).reshape(-1, 4)
            flatten_score = np.concatenate(scoreses)
            keep = nms(bboxeses, flatten_score, iou_threshold=0.3)
            new_boxes = bboxeses[keep]
            new_scores = flatten_score[keep]
        else:
            new_boxes = np.zeros((0, 4), dtype=np.float32)
            new_scores = np.array([], dtype=np.float32)

        # prepare writer
        outFeat = QgsFeature()
        fields = QgsFields()
        fields.append(QgsField('Score', QVariant.Double, 'double', 10, 11))
        outFeat.setFields(fields)

        # Prepare sink for output
        type_val = self.parameterAsEnum(parameters, self.TYPE, context)
        type_opt = geom_type(type_val)
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT, context, fields, type_opt, source.crs())

        for jk in range(new_boxes.shape[0]):

            b = np.array(new_boxes[jk,:]).astype(int)
            c = new_scores[jk]

            x1 = b[0]
            y1 = b[1]
            x2 = b[2]
            y2 = b[3]

            # Get centorid
            xc  = (x1 + x2) / 2
            yc  = (y1 + y2) / 2
            (coor_x, coor_y)  = pixel2coord(ds, xc, yc)
            centroid = QgsPoint(coor_x, coor_y)

            # Get geo coordinate of bbox
            (coor_x1, coor_y1)  = pixel2coord(ds, x1, y1)
            (coor_x2, coor_y2)  = pixel2coord(ds, x2, y1)
            (coor_x3, coor_y3)  = pixel2coord(ds, x2, y2)
            (coor_x4, coor_y4)  = pixel2coord(ds, x1, y2)
            polygon = [[QgsPointXY(coor_x1, coor_y1), QgsPointXY(coor_x2, coor_y2), QgsPointXY(coor_x3, coor_y3), QgsPointXY(coor_x4, coor_y4)]]
            diameter = coor_x2 - coor_x1

            if type_val == 0:
                # -- Point --
                outFeat.setGeometry( centroid )
            elif type_val == 1:
                # -- Bbox --
                outFeat.setGeometry( QgsGeometry.fromPolygonXY(polygon) )
            elif type_val == 2:
                # -- Circle --
                circle = QgsCircle.fromCenterDiameter(centroid, diameter).toPolygon().asWkt()
                outFeat.setGeometry( QgsGeometry.fromWkt(circle) )

            outFeat.setAttribute(0, str(c))

            sink.addFeature(outFeat, QgsFeatureSink.FastInsert)
        
        bboxes.clear()
        scoreses.clear()

        return {self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'OPTIMAL-IPB'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def shortHelpString(self):
        return self.tr("OPTIMAL-IPB (Oil Palm Trees Identification based on Machine Learning – IPB University) is an open access plugin in Quantum GIS software used to detect oil palm trees canopy on high-resolution satellite images. \n\nThis plugin was developed based on deep learning models on Retinanet architecture implemented on the repository by Fizyr. Some modifications were applied to enhance the model’s accuracy in detecting oil palm trees canopy as small objects. \n\nHow to use: \n\n1. Input your raster layer. \n\n2. Select model previously downloaded from our repository. \n\n3. Adjust mAP (mean Average Precission). default:0.5. \n\n4. Select output type from point, bounding box or circle. \n\n5. Select your output layer to save. \n\n5. Click run. \n\nOPTIMAL-IPB was built by researchers from the Center for Regional System, Analysis, Planning and Development (P4W/CRESTPENT), IPB University, Indonesia. It was based on research funded by RISPRO program held by the Indonesia Endowment Fund for Education (LPDP) – the Ministry of Finance.")

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def icon(self):
        icon = QIcon(os.path.join(cmd_folder, 'logo.png'))
        return icon

    def createInstance(self):
        return OptimalIpbAlgorithm()
